from peewee import *
from . import base


class Codes_bsn(base.BaseModel):
	pet_file = CharField(null=True)
	wq_file = CharField(null=True)
	pet = IntegerField()
	event = IntegerField() #not used
	crack = IntegerField()
	swift_out = IntegerField()
	sed_det = IntegerField()
	rte_cha = IntegerField()
	deg_cha = IntegerField() #not used
	wq_cha = IntegerField() #not used
	nostress = IntegerField()
	cn = IntegerField() #not used
	c_fact = IntegerField() #not used
	carbon = IntegerField()
	lapse = IntegerField()
	uhyd = IntegerField()
	sed_cha = IntegerField() #not used
	tiledrain = IntegerField()
	wtable = IntegerField()
	soil_p = IntegerField()
	gampt = IntegerField()
	atmo_dep = CharField() #not used???
	stor_max = IntegerField() #not used
	qual2e = IntegerField() #formerly i_fpwet
	gwflow = IntegerField(default=0)
	idc_till = IntegerField(default=3)


class Parameters_bsn(base.BaseModel):
	lai_noevap = DoubleField()
	sw_init = DoubleField()
	surq_lag = DoubleField()
	adj_pkrt = DoubleField()
	adj_pkrt_sed = DoubleField()
	lin_sed = DoubleField()
	exp_sed = DoubleField()
	orgn_min = DoubleField()
	n_uptake = DoubleField()
	p_uptake = DoubleField()
	n_perc = DoubleField()
	p_perc = DoubleField()
	p_soil = DoubleField()
	p_avail = DoubleField()
	rsd_decomp = DoubleField()
	pest_perc = DoubleField()
	msk_co1 = DoubleField()
	msk_co2 = DoubleField()
	msk_x = DoubleField()
	nperco_lchtile = DoubleField()
	evap_adj = DoubleField()
	scoef = DoubleField()
	denit_exp = DoubleField()
	denit_frac = DoubleField()
	man_bact = DoubleField()
	adj_uhyd = DoubleField()
	cn_froz = DoubleField()
	dorm_hr = DoubleField()
	plaps = DoubleField()
	tlaps = DoubleField()
	n_fix_max = DoubleField()
	rsd_decay = DoubleField()
	rsd_cover = DoubleField()
	urb_init_abst = DoubleField()
	petco_pmpt = DoubleField()
	uhyd_alpha = DoubleField()
	splash = DoubleField()
	rill = DoubleField()
	surq_exp = DoubleField()
	cov_mgt = DoubleField()
	cha_d50 = DoubleField()
	co2 = DoubleField()
	day_lag_max = DoubleField()
	igen = IntegerField()


class Carbon_bsn(base.BaseModel):
	init_seq = DoubleField()
	init_microb = DoubleField()
	init_slow = DoubleField()
	init_passive = DoubleField()
	koc_c = DoubleField()
	solc_ratio = DoubleField()
	till_eff_days = DoubleField()
	manure_c_frac = DoubleField()
	bio_consol = DoubleField()
	till_consol = DoubleField()
	tmpf_eqn = IntegerField()
	watf_eqn = IntegerField()
	t_cbn_min = DoubleField()
	t_cbn_opt = DoubleField()
	t_cbn_max = DoubleField()
	bmix_a = DoubleField()
	bmix_b = DoubleField()
	bmix_c = DoubleField()
	tillmix_a = DoubleField()
	tillmix_b = DoubleField()
	tillmix_c = DoubleField()
	sfc_rsd_photodeg = DoubleField()
	n_act_frac = DoubleField()
	cnr_cap = DoubleField()
	cnr_ref = DoubleField()
	cpr_cap = DoubleField()
	cpr_ref = DoubleField()
	mathers_method = IntegerField()


class Carbon_lyr_bsn(base.BaseModel):
	layer = IntegerField()
	hp_rate = DoubleField()
	hs_rate = DoubleField()
	microb_rate = DoubleField()
	meta_rate = DoubleField()
	str_rate = DoubleField()
	microb_top_rate = DoubleField()
	hs_hp = DoubleField()
	a1co2 = DoubleField()
	asco2 = DoubleField()
	apco2 = DoubleField()
	abco2 = DoubleField()
